parameters:
    gothick.geomoderate.paths.ext_path: %core.root_path%ext/gothick/geomoderate/
    gothick.geomoderate.paths.data_path: %gothick.geomoderate.paths.ext_path%data/
    gothick.geomoderate.paths.countries_csv: %gothick.geomoderate.paths.data_path%countries.csv
    gothick.geomoderate.paths.geolite_db: %gothick.geomoderate.paths.data_path%GeoLite2-Country.mmdb
