imports:
  - { resource: tables.yml }
  - { resource: paths.yml }
services:
  gothick.geomoderate.listener:
    class: gothick\geomoderate\event\main_listener
    arguments:
      - @user
      - @config
      - @dbal.conn
      - @log
      - @auth
      - @service_container
      - %gothick.geomoderate.tables.geomoderate%
    tags:
      - { name: event.listener }
  gothick.geomoderate.geoip2.reader:
    class: GeoIp2\Database\Reader
    arguments:
      - %gothick.geomoderate.paths.geolite_db%
